blooddonation/bloodproject/donationproject/donationapp/urls.py
from . import views
from django.urls import path
app_name = 'donationapp'
urlpatterns = [
    path('', views.allDistCen, name='allDistCen'),
    path('register', views.register, name='register_form'),
    path('login', views.login, name='login_page'),
    path('logout', views.logout, name='logout_page'),
    path('form', views.form, name='donation_form'),
    path('submit', views.submit, name='submit_form'),
    path('<slug:c_slug>/', views.allDistCen, name='districts_by_center'),
    path('<slug:c_slug>/<slug:district_slug>/', views.distDetail, name='distCendetail'),

]

blooddonation/bloodproject/donationproject/donationproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("donationapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blooddonation/bloodproject/donationproject/donationapp/models.py
from django.db import models
from django.urls import reverse


class Centers(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='center', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'center'
        verbose_name_plural = 'centers'

    def get_url(self):
        return reverse('donationapp:districts_by_center', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class District(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    center = models.ForeignKey(Centers, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='district', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'district'
        verbose_name_plural = 'districts'

    def get_url(self):
        return reverse('donationapp:distCendetail', args=[self.center.slug, self.slug])

    def __str__(self):
        return '{}'.format(self.name)

blooddonation/bloodproject/donationproject/donationapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from . models import Centers, District


def allDistCen(request, c_slug=None):
    c_page = None
    districts = None
    if c_slug!=None:
        c_page = get_object_or_404(Centers, slug=c_slug)
        districts = District.objects.all().filter(center=c_page)
    else:
        districts = District.objects.all().filter()
    return render(request, "center.html", {'center': c_page, 'districts': districts})


def distDetail(request, c_slug, district_slug):
    try:
        district = District.objects.get(center__slug=c_slug, slug=district_slug)
    except Exception as e:
        raise e
    return render(request, "district.html", {'district': district})


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/form')
        else:
            messages.info(request, "Invalid Entry")
            return redirect('/login')
    return render(request, "login.html")


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        cnf_password = request.POST['password']

        if password == cnf_password:
            if User.objects.filter(username=username).exists():
                messages.info(request, "username Taken")
                return redirect('/')
            elif User.objects.filter(email=email).exists():
                messages.info(request, "email Taken")
                return redirect('/')
            else:
                user = User.objects.create_user(username=username, email=email, password=password)
                user.save()
                print("successfully created account")
            return redirect('/')

        else:
            messages.info(request, "Password Not matching ")

        return redirect('/')
    return render(request, "register.html")


def logout(request):
    auth.logout(request)
    return redirect('/')


def form(request):
    if request.method == 'POST':
        patient_name = request.POST['patient_name']
        age = request.POST['age']
        address = request.POST['address']
        blood_group = request.POST['blood_group']
        if patient_name == form:
            if User.objects.filter(patient_name=patient_name).exists():
                messages.info(request, "user filled form already")
                return redirect('/form')
            else:
                user = User.objects.create_user(patient_name=patient_name, age=age, address=address, blood_group=blood_group)
                user.save()

                return redirect('/submit')

    return render(request, "form.html")


def submit(request):

    return render(request, "submit.html")

blooddonation/bloodproject/donationproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >

    <script src="{% static 'js/bootstrap.min.js' %}" ></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background-color:rgb(240, 128, 128);">
<div class="container-fluid">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>

   {% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
</body>
</html>

blooddonation/bloodproject/donationproject/templates/center.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if center %}
       {{ center.description|truncatewords:155 }}
   {% else %}
        Welcome to BD camp where you can donate blood for giving new life........
   {% endif %}
{% endblock %}
{% block title %}
   {% if center %}
       {{ center.name }}--  CAMP
   {% else %}
         BLOOD_DONATION
   {% endif %}
{% endblock %}
{% block content %}
{% if center %}
     <div>
         <div>
             <p><a href="{% url 'donationapp:allDistCen' %}"><b>OUR DONATION CENTERS</b></a></p>
         </div>
     </div>
{% endif %}
<div>
    {% if center %}
    <img src="{{center.image.url}}" alt="{{center.name}}" width="300px" height="300px">
</div>
   <br>
<div>
     <h1>{{center.name}}</h1>
     <p>{{center.description}}</p>
</div>
    {% else %}
<div>
    <img src="{% static 'img/donation.jpg' %}" width="1325px">
</div>
<br>
<div>
    <h2>Our Collect Centers</h2>
    <p><b>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

        It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ‘Content here, content here’, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ‘lorem ipsum’ will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</b></p>
</div>
    {% endif %}
<div>
    <div>
        {% for center in centers %}
        <div>
            <div>
                <a href="{{center.get_url}}"><img src="{{center.image.url}}" alt="{{center.name}}" width="300" height="300"> </a>
                <div>
                    <h4>{{center.name}}</h4>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
    <div class="container">
        <button class="btn btn-danger" type="button"><a href="{% url 'donationapp:login_page' %}"><b>BLOOD BANK</b></a></button>
    </div>
{% endblock %}

blooddonation/bloodproject/donationproject/templates/district.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

       {{ district.description|truncatewords:155 }}

{% endblock %}
{% block title %}
   {% if center %}
       {{ district.name }}-- BD CAMP
   {% endif %}
{% endblock %}
{% block content %}
<div>
    <div>
        <p><a href="{% url 'donationapp:allDistCen' %}">HOME</a>|<a href="{{district.center.get_url}}">{{district.center}}</a>|{{district.name}}</p>
    </div>
</div>
<br>
<div>
    <div>
        <div>
            <h1>{{district.name.url}}</h1>
        </div>
    </div>
<div>
    <div>
        <h1>{{district.name}}</h1>
        <p>{{district.description}}</p>
    </div>
</div>
</div>
{% endblock %}

blooddonation/bloodproject/donationproject/templates/footer.html
<div>
    <p><center>&copy; BD TECH PVT LTD. All rights Reserved</center></p>
</div>

blooddonation/bloodproject/donationproject/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DONATION FORM</title>
</head>
<body style="background-color:rgb(178, 34, 34);">
<h1><b>BLOOD DONATION FORM BY BD TECH PVT LTD </b></h1>
<form action="form" method="post">
    {% csrf_token %}
         <input type="text" name="patient_name" placeholder="Enter your patient_name" style="background-color:rgb(233, 150, 122)"><br>
         <input type="number" name="age" placeholder="Enter your age" style="background-color:rgb(233, 150, 122)"><br>
         <input type="text" name="address" placeholder="Enter your address" style="background-color:rgb(233, 150, 122)"><br>
         <input type="text" name="blood_group" placeholder="Enter your blood_group" style="background-color:rgb(233, 150, 122)"><br>
    <div>

                <div class="row">
                  <div class="col-md-6 mb-6 ">

                    <select class="select" style="background-color:rgb(233, 150, 122)">
                        {% for cen in links %}
                      <option value="1" href="{{cen.get_url}}" style="background-color:rgb(233, 150, 122)">{{cen.name}}</option>
                        {% endfor %}

                    </select>

                  </div>
                  <div class="col-md-6 mb-4">
                    <select class="select" style="background-color:rgb(233, 150, 122)">

                         {% for dist in dlinks %}

                      <option value="1" herf="{{dist.get.url}}" style="background-color:rgb(233, 150, 122)">{{dist.name}}</option>

                         {% endfor %}


                    </select>

                  </div>
                </div>
    </div>

    <button class="btn btn-danger" type="button" style="background-color:rgb(255, 127, 80)"><a href="{% url 'donationapp:submit_form' %}"><b>SUBMIT</b></a></button>
    <button class="btn btn-danger" type="button" style="background-color:rgb(255, 127, 80)"><a href="{% url 'donationapp:logout_page' %}"><b>LOGOUT</b></a></button>



</form>
<div>
    <p><center>&copy; BD TECH PVT LTD. All rights Reserved</center></p>
</div>
</body>
</html>

blooddonation/bloodproject/donationproject/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'donationapp:allDistCen' %}"><img src="{% static 'img/blood.jpg' %}" alt="logoimage" width="130px" height="130px"></a>
  </center>
</header>

blooddonation/bloodproject/donationproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LOGIN</title>
</head>
<body style="background-color:rgb(178, 34, 34);">
<h1> LOGIN TO BD TECH PVT LTD</h1>
<form action="login" method="post">
    {% csrf_token %}
     <input type="text" name="username" placeholder="Enter your username" style="background-color:rgb(233, 150, 122)"><br>
     <input type="password" name="password" placeholder="Enter your password" style="background-color:rgb(233, 150, 122)"><br>
     <input type="submit" style="background-color:rgb(139, 0, 0)">
    <button class="btn btn-danger" type="button" style="background-color:rgb(255, 127, 80)"><a href="{% url 'donationapp:register_form' %}"><b>Register</b></a></button>
</form>
<div>
    <p>&copy; BD TECH PVT LTD. All rights Reserved</p>
</div>
</body>
</html>

blooddonation/bloodproject/donationproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light " style="background-color:rgb(100, 149, 237)">
  <div class="container">
    <a class="navbar-brand" href="{% url 'donationapp:allDistCen' %}">HOME</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li>Hello{{user.username}}</li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'donationapp:logout_page' %}"> LOGOUT </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'donationapp:login_page' %}">LOGIN</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'donationapp:register_form' %}">REGISTER</a>
        </li>
        {% endif %}

        <li class="nav-item dropdown {% if 'donationapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            CENTERS
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

            {% for cen in links %}
            <li><a class="dropdown-item" href="{{cen.get_url}}">{{cen.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

blooddonation/bloodproject/donationproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>REGISTER</title>


</head>
<body style="background-color:rgb(178, 34, 34);">
<h1>REGISTRATION FOR BD TECH PVT LTD</h1>
<form action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter your username" style="background-color:rgb(233, 150, 122)"><br>
    <input type="email" name="email" placeholder="Enter your email" style="background-color:rgb(233, 150, 122)"><br>
    <input type="password" name="password" placeholder="Enter your password" style="background-color:rgb(233, 150, 122)"><br>
    <input type="password" name="cnf_password" placeholder="Enter your password1" style="background-color:rgb(233, 150, 122)"><br>
    <input type="submit" style="background-color:rgb(139, 0, 0)" href="{% url 'donationapp:login_page' %}"><br>
</form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
<div>
    <p>&copy; BD TECH PVT LTD. All rights Reserved</p>
</div>
</body>
</html>

blooddonation/bloodproject/donationproject/templates/submit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>submitted</title>
</head>
<body style="background-color:rgb(178, 34, 34);">
<h1><b>the form is submitted successfully </b></h1>
<p>please click<a href="{% url 'donationapp:allDistCen' %}"> <b>Here</b> </a>go Home</p>
<div>
    <p><center>&copy; BD TECH PVT LTD. All rights Reserved</center></p>
</div>
</body>
</html>

blooddonation/bloodproject/donationproject/templates/svr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DONATION FORM</title>
</head>
<body style="background-color:rgb(178, 34, 34);">
<h1><b>BLOOD DONATION FORM BY BD TECH PVT LTD </b></h1>
<form action="form" method="post">
    {% csrf_token %}
         <input type="text" name="patient_name" placeholder="Enter your patient_name" style="background-color:rgb(233, 150, 122)"><br>
         <input type="number" name="age" placeholder="Enter your age" style="background-color:rgb(233, 150, 122)"><br>
         <input type="text" name="address" placeholder="Enter your address" style="background-color:rgb(233, 150, 122)"><br>
         <input type="text" name="blood_group" placeholder="Enter your blood_group" style="background-color:rgb(233, 150, 122)"><br>
    </div>

                <div class="row">
                  <div class="col-md-6 mb-6">

                    <select class="select" style="background-color:rgb(233, 150, 122)">
                      <option value="1" style="background-color:rgb(233, 150, 122)">district</option>
                      <option value="2" style="background-color:rgb(233, 150, 122)">ERNAKULAM</option>
                      <option value="3" style="background-color:rgb(233, 150, 122)">KANNUR</option>
                      <option value="4" style="background-color:rgb(233, 150, 122)">KOTTAYAM</option>
                      <option value="5" style="background-color:rgb(233, 150, 122)">KOZHIKODE</option>
                      <option value="6" style="background-color:rgb(233, 150, 122)">THIRUVANANTHAPURAM</option>
                      <option value="6" style="background-color:rgb(233, 150, 122)">THRISSUR</option>
                    </select>

                  </div>
                  <div class="col-md-6 mb-4">

                    <select class="select" style="background-color:rgb(233, 150, 122)">
                      <option value="1" style="background-color:rgb(233, 150, 122)">center</option>
                      <option value="2" style="background-color:rgb(233, 150, 122)">ER-ALUVA</option>
                      <option value="3" style="background-color:rgb(233, 150, 122)">ER-VYTILA</option>
                      <option value="4" style="background-color:rgb(233, 150, 122)">ER-EDAPALLY</option>
                      <option value="5" style="background-color:rgb(233, 150, 122)">CNN-THALASSERY</option>
                      <option value="6" style="background-color:rgb(233, 150, 122)">CNN-MUZAPPILANGAD</option>
                      <option value="7" style="background-color:rgb(233, 150, 122)">CNN-PAYYANBALAM</option>
                      <option value="8" style="background-color:rgb(233, 150, 122)">CNN-PARASSINIKADAM</option>
                      <option value="9" style="background-color:rgb(233, 150, 122)">KT-PALA</option>
                      <option value="10" style="background-color:rgb(233, 150, 122)">KT-ETTUMANUR</option>
                      <option value="11" style="background-color:rgb(233, 150, 122)">KT-VAIKOM</option>
                      <option value="12" style="background-color:rgb(233, 150, 122)">KT-THIRUNAKARA</option>
                      <option value="13" style="background-color:rgb(233, 150, 122)">KOZ-SM.STREET</option>
                      <option value="14" style="background-color:rgb(233, 150, 122)">KOZ-KAPPAD</option>
                      <option value="15" style="background-color:rgb(233, 150, 122)">KOZ-BEYORE</option>
                      <option value="16" style="background-color:rgb(233, 150, 122)">KOZ-MANANCHIRA</option>
                      <option value="17" style="background-color:rgb(233, 150, 122)">TVPM-KOVALAM</option>
                      <option value="19" style="background-color:rgb(233, 150, 122)">TVPM-ATTUKAL</option>
                      <option value="20" style="background-color:rgb(233, 150, 122)">TVPM-VIZHINJAM</option>
                      <option value="21" style="background-color:rgb(233, 150, 122)">TVPM-SHANGHUMUKHAM</option>
                      <option value="22" style="background-color:rgb(233, 150, 122)">TCR-CHAVAKKAD</option>
                      <option value="23" style="background-color:rgb(233, 150, 122)">TCR-GURUVAYUR</option>
                      <option value="24" style="background-color:rgb(233, 150, 122)">TCR-CHALAKUDI</option>
                      <option value="25" style="background-color:rgb(233, 150, 122)">TCR-KODUNGALLUR</option>
                    </select>

                  </div>
                </div>
    </div>

              <button class="btn btn-danger" type="button" style="background-color:rgb(255, 127, 80)"><a href="{% url 'donationapp:donation_form' %}"><b>SUBMIT</b></a></button>
               <p>please click<a href="{% url 'donationapp:allDistCen' %}">Here</a>go Home</p>
              <button class="btn btn-danger" type="button" style="background-color:rgb(255, 127, 80)"><a href="{% url 'donationapp:logout_page' %}"><b>LOGOUT</b></a></button>



</form>

</body>
</html>